name: release
on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
      - name: Execute Gradle build
        run: ./gradlew -PprojectVersion=${{ github.ref_name }} test assemble installDist
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/install
          retention-days: 1
      - name: Archive distribution
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: build/distributions
          retention-days: 1

  build-push-docker:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64/v8
            runner: ubuntu-24.04-arm
    name: Build Docker Image for ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    needs: build-gradle
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up cosign
        uses: sigstore/cosign-installer@main

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: build/install

      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: distribution
          path: build/distributions

      - name: Build and publish container image by digest
        uses: docker/build-push-action@v6
        id: build_push
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          provenance: false
          platforms: ${{ matrix.platform }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ github.ref_name }}
          outputs: type=image,name=ghcr.io/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
      - name: sign container image
        run: |
          cosign sign --yes --key env://COSIGN_KEY ghcr.io/${{ env.IMAGE_NAME }}@${{ steps.build_push.outputs.digest }}
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build_push.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge images
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up cosign
        uses: sigstore/cosign-installer@main

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create \
          --tag ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
          --tag ghcr.io/${{ env.IMAGE_NAME }}:latest \
          $(printf 'ghcr.io/${{ env.IMAGE_NAME }}@sha256:%s ' *)

      - name: Check images
        run: |
          docker buildx imagetools inspect ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          cosign verify --key cosign.pub ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

  generate-example-site:
    runs-on: ubuntu-latest
    needs: build-gradle
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: build/install

      - name: Set up environment
        run: |
          sudo apt-get install -y graphviz
          chmod +x build/install/structurizr-site-generatr/bin/structurizr-site-generatr

      - name: Generate example site
        run: >
          build/install/structurizr-site-generatr/bin/structurizr-site-generatr generate-site
          --git-url ${{ github.server_url }}/${{ github.repository }}.git
          --workspace-file docs/example/workspace.dsl
          --assets-dir docs/example/assets
          --branches main
          --default-branch main
          --version ${{ github.ref_name }}

      - name: Upload example site as GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/site

  publish-example-site:
    runs-on: ubuntu-latest
    needs: [merge, generate-example-site]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy example site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-draft-release:
    runs-on: ubuntu-latest
    needs: publish-example-site
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: distribution
          path: build/distributions

      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --draft \
            --title "${{ github.ref_name }}"
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} ./build/distributions/*
